platform :ios, '13.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/volcengine/volcengine-specs.git'

project 'sdk_uniapp_iosDemo.xcodeproj'
use_frameworks! :linkage => :static

require_relative 'scripts/uniapp_module_config'
require_relative 'scripts/uniapp_uts_plugins'
require_relative 'uniapp_config' if File.exist?(File.join(__dir__, 'uniapp_config.rb'))

uniapp_subspecs = [
  'Core',
#  'Accelerometer',
  'Audio',
  'CameraGallery',
  'Contacts',
  'File',
  'Messaging',
  'Orientation',
  'Proximity',
  'XMLHttpRequest',
  'Zip',
#  'Barcode',
  'Canvas',
#  'Video',
  'Fingerprint',
#  'FaceId',
#  'BlueTooth',
  'Sqlite',
  'IBeacon',
  'Log',
  'Geolocation',
#  'Geolocation-Baidu',
#  'Geolocation-Gaode',
  'Geolocation-Tencent',
 # 'Map-Baidu',
#  'Map-Gaode',
 # 'Map-Google',
#  'Oauth',
 # 'Oauth-Univerify',
 # 'Oauth-Sina',
#  'Oauth-QQ',
#  'Oauth-Wechat',
 # 'Oauth-Wechat-PaySDK',
#  'Oauth-Apple',
#  'Oauth-Google',
#  'Oauth-Facebook',
#  'Payment',
 # 'Payment-AliPay',
 # 'Payment-Wechat',
 # 'Payment-IAP',
 # 'Payment-Paypal',
 # 'Payment-Stripe',
 # 'Push',
 # 'Push-UniPush',
 # 'Push-Getui',
 # 'Push-FCM',
 # 'Share',
 # 'Share-Sina',
 # 'Share-QQ',
 # 'Share-Wechat',
 # 'Share-Wechat-PaySDK',
 # 'Speech',
 # 'Speech-Baidu',
 # 'Speech-Ifly',
 # 'LivePusher',
 # 'Statistic',
 # 'Statistic-Umeng',
 # 'Statistic-Firebase',
 # 'UIWebview',
#  'FacialRecognitionVerify',
 # 'UniAd-CSJ',
#  'UniAd-Gromore',
#  'UniAd-GDT',
#  'UniAd-KS',
 # 'UniAd-Sigmob',
 # 'UniAd-Baidu',
 # 'UniAd-WM',
 # 'UniAd-WA',
 # 'UniAd-AppLovin',
 # 'UniAd-GG',
 # 'UniAd-GG-Pangle',
 # 'UniAd-GM-Content',
 # 'UniAd-InMobi',
 # 'UniAd-IronSource',
 # 'UniAd-KS-Content',
 # 'UniAd-Liftoff',
 # 'UniAd-Meta',
 # 'UniAd-Mintegral',
 # 'UniAd-Pangle',
 # 'UniAd-Unity',
 # 'UniAd-Oct',
 # 'UniAd-FL',
 # 'UniAd-YT',
]

uniapp_plist_values = defined?(UNIAPP_PLIST_VALUES) ? UNIAPP_PLIST_VALUES : {}
uts_plugin_values = defined?(UNIAPP_UTS_PLUGIN_VALUES) ? UNIAPP_UTS_PLUGIN_VALUES : {}
uts_plugins = UniAppUTSPlugins.prepare!(
  File.join(__dir__, 'UTSPlugins'),
  sdk_path: File.join(__dir__, '..', 'SDK'),
  values: uts_plugin_values
)

target 'sdk_uniapp_iosDemo' do
pod 'xiluAdSdk', :git => 'https://github.com/xiluProject/xiluAdSdk_ios_pod', :tag => '1.0.11'
  pod 'uniapp', :path => '../SDK', :subspecs => uniapp_subspecs
  uts_plugins.each do |plugin|
    pod plugin[:pod_name], :path => plugin[:pod_path]
  end
end

post_install do |installer|
  UniAppModuleConfig.apply(
    uniapp_subspecs,
    plist_values: uniapp_plist_values,
    uts_plugins: uts_plugins
  )
end
